import { SVGProps } from "react"

export type IconName =
  | "arrow-back-outline"
  | "arrow-forward-outline"
  | "arrow-ios-back-outline"
  | "arrow-ios-back"
  | "arrow-ios-Down-outline"
  | "arrow-ios-forward-outline"
  | "arrow-ios-forward"
  | "arrow-ios-Up"
  | "Block-1"
  | "Block"
  | "bookmark-outline"
  | "bookmark"
  | "calendar"
  | "calendar-outline"
  | "checkmark-outline"
  | "close-outline"
  | "color-palette-outline"
  | "close"
  | "copy"
  | "copy-outline"
  | "credit-card-outline"
  | "credit-card"
  | "done-all-outline"
  | "edit-2-outline"
  | "edit-2"
  | "email-outline"
  | "email"
  | "expand-outline"
  | "expand"
  | "eye-off-outline"
  | "eye-off"
  | "eye-outline"
  | "eye"
  | "Fill bell"
  | "github-svgrepo-com (3) 1"
  | "heart"
  | "heart-outline"
  | "home-outline"
  | "image"
  | "home"
  | "image-outline"
  | "layers-outline"
  | "log-out-outline"
  | "layers"
  | "log-out"
  | "maximize-outline"
  | "maximize"
  | "menu-outline"
  | "message-circle-outline"
  | "message-circle"
  | "mic-outline"
  | "mic"
  | "more-horizontal-outline"
  | "more-horizontal"
  | "Outline bell"
  | "paper-plane-outline"
  | "paper-plane"
  | "pause-circle"
  | "pause-circle-outline"
  | "person-add-outline"
  | "person-add"
  | "person-outline"
  | "person-remove-outline"
  | "person-remove"
  | "person"
  | "pin-outline"
  | "pin"
  | "play-circle-outline"
  | "play-circle"
  | "plus-circle-outline"
  | "plus-square-outline"
  | "plus-circle"
  | "radio_button_checked"
  | "plus-square"
  | "radio_button_unchecked"
  | "search-outline"
  | "search"
  | "settings"
  | "trash-outline"
  | "settings-outline"
  | "trash"
  | "trending-up-outline"
  | "trending-up"

interface IconProps extends SVGProps<SVGSVGElement> {
  name: IconName
}

export const Icon = ({ name, className, ...props }: IconProps) => {
  return (
    <svg className={className} width="24" height="24" aria-hidden="true" {...props}>
      <use href={`/sprite.svg#${name}`} />
    </svg>
  )
}
