/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/gateway-testing/test-log": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations["testLog"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/prisma/prisma-test": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all users from DB (Test)
     * @description Returns a raw list of all users from the Prisma database. Only for testing purposes.
     */
    get: operations["prismaTest"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/auth/registration": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Registration
     * @description Register a new user.
     */
    post: operations["registration"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/auth/confirm-email": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Confirm email
     * @description Confirm user email using the code sent via email.
     */
    post: operations["confirmEmail"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/auth/login": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Login
     * @description Login with username/email and password. Returns an access token and sets a refresh token in cookies.
     */
    post: operations["login"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/auth/password-recovery": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Password recovery
     * @description Request a password recovery email.
     */
    post: operations["passwordRecovery"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/auth/change-password": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Change password
     * @description Change password using the recovery code.
     */
    post: operations["newPassword"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/auth/logout": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Logout
     * @description Logout the user and clear the session.
     */
    post: operations["logout"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/auth/google/client-id": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Google Client ID
     * @description Returns the Google Client ID for frontend OAuth initialization.
     */
    get: operations["getGoogleClientId"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/auth/google/login": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Google Login & Registration
     * @description Universal endpoint for Google OAuth2. If the user does not exist, it registers them automatically. If the user exists, it logs them in. In both cases, it returns an accessToken in the body and sets a refreshToken in HttpOnly cookies. No additional requests are needed after a successful call.
     */
    post: operations["googleLogin"]
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/users/check-username": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Check if username is available
     * @description Checks whether the provided username is already taken by another user.
     */
    get: operations["checkUsername"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/sessions/my-devices": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all active sessions
     * @description Returns a list of all active sessions for the current user.
     */
    get: operations["myDevices"]
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/sessions/deactivate-one/{deviceId}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Deactivate a session
     * @description Deactivate a specific session by its device ID.
     */
    delete: operations["deactivateOne"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/api/v1/sessions/deactivate-all": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Deactivate all other sessions
     * @description Terminates all active sessions for the current user, except for the current session.
     */
    delete: operations["deactivateAll"]
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    RegisterUserDto: {
      /**
       * @description Unique username
       * @example cool_user
       */
      username: string
      /**
       * Format: email
       * @description User email
       * @example user@example.com
       */
      email: string
      /**
       * @description User password
       * @example StrongPassword123!
       */
      password: string
      /**
       * @description Password confirmation
       * @example StrongPassword123!
       */
      passwordConfirmation?: string
    }
    LoginDTO: {
      /**
       * @description Username or Email. Minimum length for username is 6, maximum 30. Email format is also supported.
       * @example cool_user
       */
      usernameOrEmail: string
      /**
       * @description User password. Must contain 0-9, a-z, A-Z, and special characters.
       * @example StrongPassword123!
       */
      password: string
    }
    PasswordRecoveryDto: {
      /**
       * Format: email
       * @description User email for recovery
       * @example user@example.com
       */
      email: string
    }
    ChangePasswordDTO: {
      /**
       * @description Recovery code sent via email
       * @example 123456-abc-...
       */
      recoveryCode: string
      /**
       * @description New password for the user
       * @example NewStrongPassword123!
       */
      newPassword: string
    }
    GoogleLoginDto: {
      /**
       * @description Google authorization code
       * @example 4/0AdQt8qi...
       */
      code: string
      /**
       * @description Optional username for new users
       * @example google_user
       */
      username?: string
      /**
       * @description Redirect URI used in Google console
       * @example http://localhost:3000/auth/google/callback
       */
      redirectUri?: string
    }
    SessionViewModel: {
      /**
       * @description IP address of the device
       * @example 192.168.1.1
       */
      ip: string
      /**
       * @description Device title (Browser / OS)
       * @example Chrome / Windows
       */
      title: string
      /**
       * @description Last active date in ISO format
       * @example 2023-10-10T14:48:00.000Z
       */
      lastActiveDate: string
      /**
       * @description Unique device identifier
       * @example 123e4567-e89b-12d3-a456-426614174000
       */
      deviceId: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type SchemaRegisterUserDto = components["schemas"]["RegisterUserDto"]
export type SchemaLoginDto = components["schemas"]["LoginDTO"]
export type SchemaPasswordRecoveryDto = components["schemas"]["PasswordRecoveryDto"]
export type SchemaChangePasswordDto = components["schemas"]["ChangePasswordDTO"]
export type SchemaGoogleLoginDto = components["schemas"]["GoogleLoginDto"]
export type SchemaSessionViewModel = components["schemas"]["SessionViewModel"]
export type $defs = Record<string, never>
export interface operations {
  testLog: {
    parameters: {
      query: {
        text: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  prismaTest: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of users retrieved directly from the database */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  registration: {
    parameters: {
      query?: never
      header: {
        /** @description Google reCAPTCHA token */
        recaptcha: string
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterUserDto"]
      }
    }
    responses: {
      /** @description Registration successful */
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          /**
           * @example {
           *       "statusCode": 400,
           *       "message": "Validation failed",
           *       "errorsMessages": [
           *         {
           *           "message": "Email must be a valid email address",
           *           "field": "email"
           *         }
           *       ]
           *     }
           */
          "application/json": unknown
        }
      }
    }
  }
  confirmEmail: {
    parameters: {
      query: {
        code: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Email confirmed successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Invalid or expired code */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          /**
           * @example {
           *       "statusCode": 400,
           *       "message": "Invalid code",
           *       "errorsMessages": [
           *         {
           *           "message": "Code has expired",
           *           "field": "code"
           *         }
           *       ]
           *     }
           */
          "application/json": unknown
        }
      }
    }
  }
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginDTO"]
      }
    }
    responses: {
      /** @description Login successful */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Invalid credentials or OAuth provider required */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          /**
           * @example {
           *       "statusCode": 401,
           *       "message": "Unauthorized"
           *     }
           */
          "application/json": unknown
        }
      }
    }
  }
  passwordRecovery: {
    parameters: {
      query?: never
      header: {
        /** @description Google reCAPTCHA token */
        recaptcha: string
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordRecoveryDto"]
      }
    }
    responses: {
      /** @description Recovery email sent */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          /**
           * @example {
           *       "statusCode": 400,
           *       "message": "Validation failed",
           *       "errorsMessages": [
           *         {
           *           "message": "Email must be a valid email address",
           *           "field": "email"
           *         }
           *       ]
           *     }
           */
          "application/json": unknown
        }
      }
    }
  }
  newPassword: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordDTO"]
      }
    }
    responses: {
      /** @description Password changed successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Invalid code or passwords do not match */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          /**
           * @example {
           *       "statusCode": 400,
           *       "message": "Invalid code",
           *       "errorsMessages": [
           *         {
           *           "message": "Code is invalid or has expired",
           *           "field": "recoveryCode"
           *         }
           *       ]
           *     }
           */
          "application/json": unknown
        }
      }
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Logout successful */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          /**
           * @example {
           *       "statusCode": 401,
           *       "message": "Unauthorized"
           *     }
           */
          "application/json": unknown
        }
      }
    }
  }
  getGoogleClientId: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Client ID returned successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
    }
  }
  googleLogin: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        "application/json": components["schemas"]["GoogleLoginDto"]
      }
    }
    responses: {
      /** @description Login successful */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": unknown
        }
      }
      /** @description Invalid Google token */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          /**
           * @example {
           *       "statusCode": 401,
           *       "message": "Unauthorized"
           *     }
           */
          "application/json": unknown
        }
      }
    }
  }
  checkUsername: {
    parameters: {
      query: {
        /** @description The username to check */
        username: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Username availability status */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": {
            available?: boolean
          }
        }
      }
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          /**
           * @example {
           *       "statusCode": 400,
           *       "message": "Validation failed",
           *       "errorsMessages": [
           *         {
           *           "message": "Invalid username format",
           *           "field": "username"
           *         }
           *       ]
           *     }
           */
          "application/json": unknown
        }
      }
    }
  }
  myDevices: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of active sessions */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          "application/json": components["schemas"]["SessionViewModel"][]
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          /**
           * @example {
           *       "statusCode": 401,
           *       "message": "Unauthorized"
           *     }
           */
          "application/json": unknown
        }
      }
    }
  }
  deactivateOne: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description The unique identifier of the device/session */
        deviceId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Session successfully deactivated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          /**
           * @example {
           *       "statusCode": 401,
           *       "message": "Unauthorized"
           *     }
           */
          "application/json": unknown
        }
      }
      /** @description Forbidden to delete another user session */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          /**
           * @example {
           *       "statusCode": 403,
           *       "message": "Forbidden"
           *     }
           */
          "application/json": unknown
        }
      }
      /** @description Session not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          /**
           * @example {
           *       "statusCode": 404,
           *       "message": "Not Found",
           *       "errorsMessages": [
           *         {
           *           "message": "Session with this ID does not exist",
           *           "field": "deviceId"
           *         }
           *       ]
           *     }
           */
          "application/json": unknown
        }
      }
    }
  }
  deactivateAll: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description All other sessions successfully deactivated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          /**
           * @example {
           *       "statusCode": 401,
           *       "message": "Unauthorized"
           *     }
           */
          "application/json": unknown
        }
      }
    }
  }
}
